import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import { RootContainer } from "@/components/ui/root-container";
import { Provider as ChakraProvider } from "@/components/ui/provider";
const interSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bill Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${interSans.variable}`}>
        <ChakraProvider>
          <Toaster />
          <RootContainer>{children}</RootContainer>
        </ChakraProvider>
      </body>
    </html>
  );
}
