name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUPABASE_PROJECT_ID: ${{ secrets.TEST_SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.TEST_SUPABASE_ACCESS_TOKEN }}

      SUPABASE_DB_URL: ${{ secrets.TEST_SUPABASE_DB_URL }}
      SUPABASE_DB_PASSWORD: ${{ secrets.TEST_SUPABASE_DB_PASSWORD }}

      SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.TEST_SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link remote Supabase test instance
        run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: yes | supabase db reset --linked --no-seed
      - run: supabase db push --linked

      - name: Initialize Supabase
        run: |
          env_content="SUPABASE_URL=\"$SUPABASE_DB_URL\"\nSUPABASE_SERVICE_ROLE_KEY=\"$SUPABASE_SERVICE_ROLE_KEY\"\nNEXT_PUBLIC_SUPABASE_URL=\"$SUPABASE_DB_URL\"\nNEXT_PUBLIC_SUPABASE_ANON_KEY=\"$SUPABASE_ANON_KEY\""
          echo -e "$env_content" > .env.local

      - name: Run Playwright
        run: |
          pnpm playwright
